# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0db2800a7c4aea74222f53bcac6bf63d333ca0fde0cd7cf9dd32cda178afcb9095caf7abc5a5bb7b8955633f059db28785f27273a8285fedefcd3b145304aa35

test:
  secret_key_base: 3b78fd0ad3bd12d40075ff78915930067af4b92949879c4e3c5256104b487cb2424ac62b44d012166decb6a3ee8984c9148532c222efe59f2453434b230a169d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
